image: node:20-alpine

stages:
  - 📦push

include:
  - project: 'IUT_INF63/generic-ci'
    ref: 'main'
    file:
      - 'build/.docker-build.yml'

push-portfolio-image:
  extends: .build-and-push-docker-image
  stage: 📦push
  variables:
    DOCKERFILE_RELATIVE_PATH: "Dockerfile"
    DOCKERFILE_CONTEXT_PATH: "."
    DESTINATION_REGISTRY_IMAGE_NAME: "codefirst.iut.uca.fr/reneveu/portfolio/portfolio"
    DESTINATION_REGISTRY_IMAGE_VERSION: "$CI_COMMIT_REF_SLUG"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"