image: node:20-alpine

stages:
  - build
  - deploy

build_angular:
  stage: build
  script:
    - rm -f package-lock.json
    - npm i
    - npm run build -- --base-href ./
  artifacts:
    paths:
      - dist/angular-portfolio/browser/
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - build_angular
  script:
    - rm -rf public
    - mv dist/angular-portfolio/browser public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"